=== api-evangelist/amazon-iot-fleetwise/json-schema/iot-fleetwise-decoder-manifest-summaries-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-iot-fleetwise/refs/heads/main/json-schema/iot-fleetwise-decoder-manifest-summaries-schema.json",
  "title": "decoderManifestSummaries",
  "description": "decoderManifestSummaries schema",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "creationTime",
      "lastModificationTime"
    ],
    "properties": {
      "name": {
        "allOf": [
          {
            "$ref": "#/components/schemas/string"
          },
          {
            "description": "The name of the decoder manifest."
          }
        ]
      },
      "arn": {
        "allOf": [
          {
            "$ref": "#/components/schemas/arn"
          },
          {
            "description": "The ARN of a vehicle model (model manifest) associated with the decoder manifest. "
          }
        ]
      },
      "modelManifestArn": {
        "allOf": [
          {
            "$ref": "#/components/schemas/arn"
          },
          {
            "description": "The ARN of a vehicle model (model manifest) associated with the decoder manifest."
          }
        ]
      },
      "description": {
        "allOf": [
          {
            "$ref": "#/components/schemas/description"
          },
          {
            "description": "A brief description of the decoder manifest."
          }
        ]
      },
      "status": {
        "allOf": [
          {
            "$ref": "#/components/schemas/ManifestStatus"
          },
          {
            "description": "The state of the decoder manifest. If the status is <code>ACTIVE</code>, the decoder manifest can't be edited. If the status is marked <code>DRAFT</code>, you can edit the decoder manifest."
          }
        ]
      },
      "creationTime": {
        "allOf": [
          {
            "$ref": "#/components/schemas/timestamp"
          },
          {
            "description": "The time the decoder manifest was created in seconds since epoch (January 1, 1970 at midnight UTC time)."
          }
        ]
      },
      "lastModificationTime": {
        "allOf": [
          {
            "$ref": "#/components/schemas/timestamp"
          },
          {
            "description": "The time the decoder manifest was last updated in seconds since epoch (January 1, 1970 at midnight UTC time)."
          }
        ]
      }
    },
    "description": "Information about a created decoder manifest. You can use the API operation to return this information about multiple decoder manifests."
  }
}

=== api-evangelist/amazon-iot-fleetwise/examples/iot-fleetwise-decoder-manifest-summary-example.json
{
  "name": "example-resource",
  "arn": "arn:aws:iot:us-east-1:123456789012:thing/example",
  "modelManifestArn": "arn:aws:iot:us-east-1:123456789012:thing/example",
  "description": "example-value",
  "status": "ACTIVE",
  "creationTime": "2025-03-15T14:30:00Z",
  "lastModificationTime": "2025-03-15T14:30:00Z"
}

=== api-evangelist/amazon-iot-fleetwise/examples/iot-fleetwise-get-decoder-manifest-response-example.json
{
  "name": "example-resource",
  "arn": "arn:aws:iot:us-east-1:123456789012:thing/example",
  "description": "example-value",
  "modelManifestArn": "arn:aws:iot:us-east-1:123456789012:thing/example",
  "status": "ACTIVE",
  "creationTime": "2025-03-15T14:30:00Z",
  "lastModificationTime": "2025-03-15T14:30:00Z"
}
